export const LIST_VIDEOS = "LIST_VIDEOS";
export const FETCH_VIDEOS_ERROR = "FETCH_VIDEOS_ERROR" 
export const LOAD_VIDEOS = "LOAD_VIDEOS";
export const DELETE_ONE_VIDEO = "DELETE_ONE_VIDEO"
export const LIKE_VIDEOS = "LIKE_VIDEOS";
export const DISLIKE_VIDEO = "DISLIKE_VIDEO";
export const FILTER_CATEGORY = "FILTER_CATEGORY"
